M48
; DRILL file {KiCad (6.0.11)} date Mon Sep 18 23:50:29 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-18T23:50:29-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X2.3929Y-2.0374
T1
G00X2.3929Y-2.315
M15
G01X2.3929Y-2.3268
M16
G05
T0
M30
